# This is a simple compose file to test the storagenode during development.
# It starts a single storagenode, a satellite-api, a cockroachdb, and a redis.
# Make a copy of the testdata folder to a "test":
# cp -r testdata test

services:
  cockroach:
    command:
      - start-single-node
      - --insecure
      - --http-addr=localhost:8086
      - --store="/tmp/cockroach"
    deploy:
      replicas: 1
    image: cockroachdb/cockroach:v24.2.1
    ports:
      - mode: ingress
        target: 26257
        published: 26257
  redis:
    command:
      - redis-server
    deploy:
      replicas: 1
    image: redis:6.0.9
  satellite-api:
    command:
      - satellite
      - run
      - api
      - --defaults=dev
      - --identity-dir=/var/lib/storj/.local/share/storj/identity/satellite-api/
    deploy:
      replicas: 1
    environment:
      STORJUP_ROLE: satellite-api
      STORJ_ADDRESS: 0.0.0.0:7777
      STORJ_CONSOLE_ADDRESS: 0.0.0.0:10000
      STORJ_CONSOLE_AUTH_TOKEN_SECRET: my-suppa-secret-key
      STORJ_CONSOLE_EXTERNAL_ADDRESS: http://localhost:10000/
      STORJ_CONSOLE_GATEWAY_CREDENTIALS_REQUEST_URL: http://localhost:8888
      STORJ_CONSOLE_LINKSHARING_URL: http://localhost:9090
      STORJ_CONSOLE_OPEN_REGISTRATION_ENABLED: "true"
      STORJ_CONSOLE_PUBLIC_LINKSHARING_URL: http://localhost:9090
      STORJ_CONSOLE_RATE_LIMIT_BURST: "10000"
      STORJ_CONSOLE_SIGNUP_ACTIVATION_CODE_ENABLED: "false"
      STORJ_CONTACT_EXTERNAL_ADDRESS: satellite-api:7777
      STORJ_DATABASE: cockroach://root@cockroach:26257/master?sslmode=disable
      STORJ_DEBUG_ADDR: 0.0.0.0:11111
      STORJ_DEFAULTS: dev
      STORJ_IDENTITY_DIR: /var/lib/storj/.local/share/storj/identity/satellite-api/
      STORJ_LIVE_ACCOUNTING_STORAGE_BACKEND: redis://redis:6379?db=0
      STORJ_LOG_LEVEL: debug
      STORJ_MAIL_FROM: Storj <storj-up@storj.io>
      STORJ_MAIL_SMTP_SERVER_ADDRESS: smtp.gmail.com:587
      STORJ_METAINFO_DATABASE_URL: cockroach://root@cockroach:26257/metainfo?sslmode=disable
      STORJ_METAINFO_RATE_LIMITER_ENABLED: "false"
      STORJ_METRICS_APP_SUFFIX: sim
      STORJ_ORDERS_ENCRYPTION_KEYS: 0100000000000000=0100000000000000000000000000000000000000000000000000000000000000
      STORJ_OVERLAY_NODE_MINIMUM_DISK_SPACE: 500MB
      STORJ_ROLE: satellite-api
      STORJ_SERVER_ADDRESS: 0.0.0.0:7777
      STORJ_SERVER_EXTENSIONS_REVOCATION: "false"
      STORJ_SERVER_PRIVATE_ADDRESS: 0.0.0.0:5559
      STORJ_SERVER_REVOCATION_DBURL: redis://redis:6379?db=1
      STORJ_SERVER_USE_PEER_CA_WHITELIST: "false"
      STORJ_USE_PREDEFINED_IDENTITY: "1"
      STORJ_VERSION_SERVER_ADDRESS: https://version.storj.io
      STORJ_WAIT_FOR_DB: "true"
    image: img.dev.storj.io/storjup/storj:1.114.6
    depends_on:
      - cockroach
      - redis
    ports:
      - mode: ingress
        target: 7777
        published: 7777
        protocol: tcp
      - mode: ingress
        target: 10000
        published: 10000
        protocol: tcp
  storagenode:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    depends_on:
      - satellite-api
    environment:
      SETUP: "false"
      STORJ_CONSOLE_ADDRESS: 0.0.0.0:30000
      STORJ_CONTACT_EXTERNAL_ADDRESS: storagenode:30001
      STORJ_DEBUG_ADDR: 0.0.0.0:11111
      STORJ_DEFAULTS: dev
      STORJ_IDENTITY_DIR: /app/identity
      STORJ_LOG_LEVEL: debug
      STORJ_METRICS_APP_SUFFIX: sim
      STORJ_OPERATOR_EMAIL: storage9@mail.test
      STORJ_OPERATOR_WALLET: "0x0123456789012345678901234567890123456789"
      STORJ_ROLE: storagenode
      STORJ_SERVER_ADDRESS: 0.0.0.0:30001
      STORJ_SERVER_EXTENSIONS_REVOCATION: "false"
      STORJ_SERVER_PRIVATE_ADDRESS: 0.0.0.0:30002
      STORJ_SERVER_USE_PEER_CA_WHITELIST: "false"
      STORJ_STORAGE2_MONITOR_MINIMUM_DISK_SPACE: "0"
      STORJ_STORAGE2_TRUST_SOURCES: 12whfK1EDvHJtajBiAUeajQLYcWqxcQmdYQU5zX5cCf6bAxfgu4@satellite-api:7777
      STORJ_STORAGE_ALLOCATED_DISK_SPACE: 1G
      STORJ_VERSION_SERVER_ADDRESS: https://version.storj.io
      STORJ_WAIT_FOR_SATELLITE: "true"
    volumes:
      - ./test/config:/app/config
      - ./test/identity:/app/identity
    ports:
      - mode: ingress
        target: 30000
        published: 30000
        protocol: tcp

networks: {}
