#!/bin/bash

set -euo pipefail

## Run supervisor with a void (accepts signal but does not exit) binary as storagenode

mkdir -p ./test/config/bin

cp -r ./testdata/config ./test/
cp -r ./testdata/identity ./test/
cp ./testdata/binaries/void ./test/config/bin/storagenode

docker compose up --build
